apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-config
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.configSize | quote }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cache
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.cacheSize | quote }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-media
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.mediaSize | quote }}
