apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-config
  namespace: home-media
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.configSize | quote }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cache
  namespace: home-media
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.cacheSize | quote }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-media
  namespace: home-media
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.mediaSize | quote }}
