image:
  repository: jellyfin/jellyfin
  tag: "2026010505"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "250m"
    memory: "500Mi"

persistence:
  storageClassName: standard
  configSize: 5Gi
  cacheSize: 5Gi
  mediaSize: 20Gi

service:
  type: ClusterIP
  port: 8096
  nodePort: 30096
